# -*- coding: utf-8 -*-
"""Lista de Exercicios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lreL1psvwxKPzmb9qktxxnsMrlzAQqe7
"""
#EXERCÍCIO 1
print("Soma/Adição")
a = float(input("Digite um número: "))
b = float(input("Digite um número: "))
soma = a + b
print(f"Soma = {soma}\n")

#EXERCÍCIO 2
print("Subtração")
a = float(input("Digite um número: "))
b = float(input("Digite um número: "))
subtracao = a - b
print(f"Subtração = {subtracao}\n")

#EXERCÍCIO 3
print("Multiplicação")
a = float(input("Digite um número: "))
b = float(input("Digite um número: "))
multiplicacao = a * b
print(f"Multiplicação = {multiplicacao}\n")

#EXERCÍCIO 4
print("Divisão")
a = float(input("Digite um número: "))
b = float(input("Digite um número: "))
divisao = a / b
print(f"Divisão = {divisao}\n")

#EXERCÍCIO 5
print("Antecessor/Sucessor")
num = int(input("Digite um número: "))
antecessor = num - 1
sucessor = num + 1
print(f"O antecessor de {num} é: {antecessor}")
print(f"O sucessor de {num} é {sucessor}\n")

#EXERCÍCIO 6
print("Dobro/Triplo")
num = float(input("Digite um número: "))
dobro = num * 2
triplo = num * 3
print(f"O dobro de {num} é: {dobro}")
print(f"O triplo de {num} é: {triplo}\n")

#EXERCÍCIO 7
print("Perímetro do Retângulo")
lado1 = float(input("Digite o valor de um dos lados de um retângulo: "))
lado2 = float(input("Digite o valor do outro lado desse retângulo: "))
perimetro = (lado1 * 2) + (lado2 * 2)
print(f"O perímetro desse retângulo de lados {lado1} e {lado2} é: {perimetro}\n")

#EXERCÍCIO 8
print("Área do Triângulo")
base = float(input("Digite o valor da base de um triângulo: "))
altura = float(input("Digite o valor da altura da base desse triângulo: "))
area = (base * altura) / 2
print(f"A área desse triângulo de base {base} e altura {altura} é: {area}\n")

#EXERCÍCIO 9
print("Número: Positivo, Negativo ou Zero")
numero = int(input("Digite um número: "))

if numero > 0:
  print("Esse número é POSITIVO!\n")
elif numero < 0:
  print("Esse número é NEGATIVO!\n")
else:
  print("Esse número é ZERO!\n")

#EXERCÍCIO 10
print("Número: Par ou Ímpar")
numero = int(input("Digite um número: "))

if numero % 2 == 0:
  print("Esse número é PAR!\n")
else:
  print("Esse número é ÍMPAR!\n")

#EXERCÍCIO 11
print("Identificação do maior entre dois números")
num1 = int(input("Digite o primeiro número: "))
num2 = int(input("Digite o segundo número: "))

if num1 > num2:
  print(f"O primeiro número ({num1}) é maior que o segundo número ({num2})\n")
elif num1 < num2:
  print(f"O segundo número ({num2}) é maior que o primeiro número ({num1})\n")
else:
  print(f"Os dois números são iguais ({num1})\n")

#EXERCÍCIO 12
print("Identificação do maior entre três números")
num1 = int(input("Digite o primeiro número: "))
num2 = int(input("Digite o segundo número: "))
num3 = int(input("Digite o terceiro número: "))

if num1 > num2 and num1 > num3:
  print(f"O primeiro número ({num1}) é o maior dos três!\n")
elif num2 > num1 and num2 > num3:
  print(f"O segundo número ({num2}) é o maior dos três!\n")
elif num3 > num1 and num3 > num2:
  print(f"O terceiro número ({num3}) é o maior dos três!\n")
else:
  print(f"Os três números são iguais!\n")

#EXERCÍCIO 13
print("Quem pode votar?")
idade = int(input("Digite sua idade: "))
titulo_eleitor = input("Você tem título de eleitor?: ")

if titulo_eleitor.lower() == "sim":
  titulo_eleitor = True
else:
  titulo_eleitor = False

if idade >= 16 and titulo_eleitor:
  print("Você pode votar!\n")
else:
  print("Você não pode votar!\n")

#EXERCÍCIO 14
print("Quem pode dirigir?")
idade = int(input("Digite sua idade: "))
cnh = input("Você possui CNH?: ")

if cnh.lower() == "sim":
  cnh = True
else:
  cnh = False

if idade >= 18 and cnh:
  print("Você pode dirigir!\n")
else:
  print("Você não pode dirigir!\n")

#EXERCÍCIO 15
print("Desconto de 10% na compra à vista")
preco = float(input("Digite o valor do produto: "))
avista = input("Deseja pagar à vista?: ")

if avista.lower() == "sim":
  avista = True
  desconto = preco * 0.1
  precodesconto = preco - desconto
  print(f"Desconto de 10% {desconto}")
  print(f"Valor final: {precodesconto}")
else:
  avista = False
  print(f"Valor da compra: {preco}")

#EXERCÍCIO 16
print("Aumento de 15% no salário até 2000 reais")
salario = float(input("Digite o valor do seu salário: "))

if salario <= 2000:
  aumento = salario * 0.15
  salario = salario + aumento
  print(f"O seu salário com aumento de 15% é: R${salario}\n")
else:
  print("O seu salário não se aplica ao aumento!\n")

#EXERCÍCIO 17
print("Declaração de intervalo de 10 a 50")
num = int(input("Digite um número entre 10 e 50: "))
if num >= 10 and num <=50:
  print("O número está dentro do intervalo!!!")
else:
  print("O número está fora do intervalo!!!")

#EXERCÍCIO 18
print("Senha correta: cadastro e autenticação")
senha_cadastro = input("CADASTRO - Crie uma senha: ")
print("Senha cadastrada!!!")

senha_login = input("LOGIN - Digite sua senha: ")

if senha_cadastro == senha_login:
  print("Acesso Autenticado!")
else:
  print("Senha incorreta!")

#EXERCÍCIO 19
print("Entrada de um evento: 18 anos e com ingresso")
idade = int(input("Digite sua idade: "))
ingresso = input("Você possui ingresso?: ")

if ingresso.lower() == "sim":
  ingresso = True
else:
  ingresso = False

if idade >= 18 and ingresso:
  print("Você pode entrar!\n")
else:
  print("Você não pode entrar!\n")

#EXERCÍCIO 20
print("Calculadora Simples")
num1 = float(input("Digite um número: "))
print("Operações: (+) (-) (*) (/) (%) (**)")
op = str(input("Escolha qual operação você deseja realizar: "))
num2 = float(input("Digite outro número: "))

if op == "+":
  soma = num1 + num2
  print(f"({num1}) + ({num2}) = {soma}")
elif op == "-":
  sub = num1 - num2
  print(f"({num1}) - ({num2}) = {sub}")
elif op == "*":
  mul = num1 * num2
  print(f"({num1}) * ({num2}) = {mul}")
elif op == "/":
  div = num1 / num2
  print(f"({num1}) / ({num2}) = {div:.2f}")
elif op == "%":
  resto = num1 % num2
  print(f"({num1}) % ({num2}) = {resto}")
elif op == "**":
  pot = num1 ** num2
  print(f"({num1}) ** ({num2}) = {pot}")
else:
  print("Operação Incorreta!!!")
