# -*- coding: utf-8 -*-
"""Lista de Exercicios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lreL1psvwxKPzmb9qktxxnsMrlzAQqe7
"""

print("Soma/Adição")

a = float(input("Digite um número: "))
b = float(input("Digite um número: "))
soma = a + b
print("Soma = ", soma)

print("Subtração")

a = float(input("Digite um número: "))
b = float(input("Digite um número: "))
subtracao = a - b
print("Subtração = ", subtracao)

print("Multiplicação")

a = float(input("Digite um número: "))
b = float(input("Digite um número: "))
multiplicacao = a * b
print("Multiplicação = ", multiplicacao)

print("Divisão")

a = float(input("Digite um número: "))
b = float(input("Digite um número: "))
divisao = a / b
print("Divisão = ", divisao)

print("Antecessor/Sucessor")
num = int(input("Digite um número: "))
antecessor = num - 1
sucessor = num + 1
print(f"O antecessor de {num} é: {antecessor}")
print(f"O sucessor de {num} é {sucessor}")

print("Dobro/Triplo")
num = float(input("Digite um número: "))
dobro = num * 2
triplo = num * 3
print(f"O dobro de {num} é: {dobro}")
print(f"O triplo de {num} é: {triplo}")

lado1 = float(input("Digite o valor de um dos lados de um retângulo: "))
lado2 = float(input("Digite o valor do outro lado desse retângulo: "))
perimetro = (lado1 * 2) + (lado2 * 2)
print(f"O perímetro desse retângulo de lados {lado1} e {lado2} é: {perimetro}")

base = float(input("Digite o valor da base de um triângulo: "))
altura = float(input("Digite o valor da altura da base desse triângulo: "))
area = (base * altura) / 2
print(f"A área desse triângulo de base {base} e altura {altura} é: {area}")

